(* Reference:
 * https://clang.llvm.org/doxygen/classclang_1_1Decl.html
 * include/clang/AST/TypeNodes.inc *)

type t =
  | AdjustedType
  | DecayedType
  | ConstantArrayType
  | DependenSizedArrayType
  | IncompleteArrayType
  | VariableArrayType
  | AtomicType
  | AttributedType
  | BlockPointerType
  | BuiltinType
  | ComplexType
  (*10 *)
  | DecltypType
  | AutoType
  | DeducedTemplateSpecializationType
  | DependentAddressSpaceType
  | DependentExtIntType
  | DependentNameType
  | DependentSizedExtVectorType
  | DependentTemplateSpecializationType
  | DependentVectorType
  | ElaboratedType
  | ExtIntType
  | FunctionNoProtoType
  | FunctionProtoType
  | InjectedClassNameType
  | MacroQualifiedType
  | ConstantMatrixType
  | DependentSizedMatrixType
  | MemberPointerType
  | ObjCObjectPointerType
  | ObjCObjectType
  | ObjCInterfaceType
  | ObjCTypeParamType
  | PackExpansionType
  | ParenType
  | PipeType
  | PointerType
  | LValueReferenceType
  | RValueReferenceType
  | SubstTemplateTypeParmPackType
  | SubstTemplateTypeParmType
  | EnumType
  | RecordType
  | TemplateSpecializationType
  | TemplateTypeParmType
  | TypeOfExprType
  | TypeOfType
  | TypedefType
  | UnaryTransformType
  | UnresolvedUsingType
  | VectorType
  | ExtVectorType
[@@deriving show]
