name: build

on: [push, pull_request]

jobs:
  check:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1.0

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-15-dev pkg-config libclang-15-dev

      - name: Build Claml
        run: |
          ./build.sh

      - name: Run test (regression)
        run: eval $(opam env) && make test
